### ISSUE TITLE
please fix it

### ISSUE THREAD

**Issue by Anagnuss** [teja156/microsoft-teams-class-attender#22]
![image](https://user-images.githubusercontent.com/74353568/98927671-20b26f00-24d9-11eb-8cea-64fff3f6ab8b.png)

**Comment by JeanS-git** [comment]
same

**Comment by Anagnuss** [comment]
I did everything according to README.txt

**Comment by JeanS-git** [comment]
me too but still the issue

**Comment by JeanS-git** [comment]
I don't know why but it still works now, I think first it was a problem due to the longer of the class name, then I think it was about the timetable -> .db <- missing in bot.py
So I add it, I removed it, and I also remove timetable, but it doesn't works.
So I tried with another class room with just 4 letter without - or _ or blank and ... It works ! 
But I already don't know why ...
And after that I tried again with a real class room and it works, i can see the database with the program

Now I have another issue : Do you we need to install Chrome instead of Chromium or Firefox ? And do we absolutly need a discord webhook ? or an online webhook can works ?
So when I launch the bot it doesn't work.
Here is the erroes :
`
1. Modify Timetable
2. View Timetable
3. Start Bot
Enter option : 3
Scheduled class 'Home' on Thursday at 14:00
bot.py:207: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 269, in <module>
    sched()
  File "bot.py", line 252, in sched
    start_browser()
  File "bot.py", line 207, in start_browser
    driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
`

Thanks

**Comment by amalthomas-exe** [comment]
@JeanS-git you have to download the drivers for that particular version of chrome that you are using, and put in the code
`driver = webdriver.Chrome('/path/to/downloaded/driver.exe')`

Then it should work

You can get the drivers here:
https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by JeanS-git** [comment]
@amalthomas-exe  Thanks for your answer, before you tell me that I was reading the other issue and saw I've to do that.
But unfortunately it was not working, and I know why.
Let me explain you :
I'm on debian 10 and I've installed Chromium
And as it doesn't works, i tried with google chrome but it doesn't work too
then I added the chromium drivers (in the file too) but still doesn't works, because the program chose first Chrome instead of Chromium
so I removed chrome
It works, so it launched chromium, the login page works but it says me : 
`To open the web app, change your browser settings to allow third-party cookies or allow certain trusted domains.`
So I did it , but there still a problem, as I always need to do this step (allow third part cookies in site permission in settings)
It seem that it always open chromium as a "new person", like a new account, so the settings are never preserved, so we need to do this steps during the process and click on try again, but it's ok I do it, but (yes again sorry) at the time for the meet it can"t join.

Here is the errors:

`
1. Modify Timetable
2. View Timetable
3. Start Bot
Enter option : 3
Scheduled class 'JEAN' on friday at 12:10
bot.py:207: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
logging in

JOINING CLASS  FOO
Traceback (most recent call last):
  File "bot.py", line 269, in <module>
    sched()
  File "bot.py", line 256, in sched
    schedule.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "bot.py", line 141, in joinclass
    i.click()
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.116)
`

**Comment by JeanS-git** [comment]
Ok this last error (can't interract with element is due to Chromium must be in "fullscreen" not for example on the left half of the screen so now it totally works !
I still have to manually deactivate the option in chromium "block third-part cookies" in settings ; site permission ; cookies, that the only issue now for me, maybe there is an option in chrome web driver ?

**Comment by amalthomas-exe** [comment]
@JeanS-git , first of all, this code has been written keeping the chrome browser in mind. That is why we have already given the required permission to the browser in the following lines of code:
`opt.add_argument("--disable-infobars")
opt.add_argument("start-maximized")
opt.add_argument("--disable-extensions")
opt.add_argument("--start-maximized")
# Pass the argument 1 to allow and 2 to block
opt.add_experimental_option("prefs", { \
    "profile.default_content_setting_values.media_stream_mic": 1, 
    "profile.default_content_setting_values.media_stream_camera": 1,
    "profile.default_content_setting_values.geolocation": 1, 
    "profile.default_content_setting_values.notifications": 1 
  })`

as you can see in `opt.add_argument("start-maximized")`, the browser window opens in a full screen, due to which the element not found error has been resolved. Also, we have provided permission to access the camera, the mic and the location, so unnecessary popups don't come up. Due to which there are fewer chances of errors.

Try to reinstall the chrome browser, and take a note of its version (mainly found on the about page of chrome). Now go to this link:
https://sites.google.com/a/chromium.org/chromedriver/home

and download the driver for that particular version of chrome browser
now put in the code:
`driver = webdriver.Chrome('/path/to/downloaded/driver.exe')`

It should work this time.

Keep me updated 😄

**Comment by JeanS-git** [comment]
@amalthomas-exe 
Hi thanks for your answer.
To avoid using Chrome instead of Chromium I just set up 1 option to disable the "block ... cookies"
```
opt.add_experimental_option("prefs", { \
    "profile.block_third_party_cookies": False,
    "profile.default_content_setting_values.media_stream_mic": 1, 
```
And I was stuck at the page "Download linux app" so I added a `driver.refresh()` after the login call
```
	if("login.microsoftonline.com" in driver.current_url):
		login()
		driver.refresh() #added to avoid staying stuck on page "download linux app"
```

And now it totally works (with chromium :smile: )

**Comment by amalthomas-exe** [comment]
@JeanS-git I also had the same issue, where it would get stuck at the download windows app page, so I made the program to click on that button that says to use the web version and cross that page. Anyway, happy that your issue is resolved 😄

**Comment by MariusMRN** [comment]
@amalthomas-exe  can you give to us the program to click on web version :D I'm getting stucked here too

**Comment by amalthomas-exe** [comment]
@MariusMRN sure!
`driver.find_element_by_class_name("use-app-lnk").click()`
`sleep(5)`

**Comment by amalthomas-exe** [comment]
@JeanS-git and @MariusMRN have your issues been resolved???

**Comment by JeanS-git** [comment]
@amalthomas-exe  yes !
